services:
  apache:
    build: . 
    user: $UID:$GID
    network_mode: host
    env_file:
        - .env
    volumes:
      - ./apache:/var/www/html:Z
      - ./fail2ban:/etc/fail2ban:Z
      - ./webConf:/etc/apache2:Z
      - ./waf:/etc/modsecurity:Z
    privileged: true
    container_name: apache-healthapp
  mariaDB:
    image: mariadb
    env_file:
        - .env
    network_mode: host
    volumes:
      - ./mariaDB/:/var/lib/mysql:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: lamp-mariaDB-1

